#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init(void);

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_COUNTER_L_RUN (0)
#define SCT_OUTPUTPRELOAD_COUNTER_L_RUN (1)
#define SCT_OUTPUT_COUNTER_H_RUN (1)
#define SCT_OUTPUTPRELOAD_COUNTER_H_RUN (0)
#define SCT_OUTPUT_STATE_1 (2)
#define SCT_OUTPUTPRELOAD_STATE_1 (0)
#define SCT_OUTPUT_STATE_2 (3)
#define SCT_OUTPUTPRELOAD_STATE_2 (0)


/* Match register reload macro definitions */
#define reload_deactivate_L(value) LPC_SCT->MATCHREL_L[0] = value;
#define reload_activate_L(value) LPC_SCT->MATCHREL_H[0] = value;
#define reload_activate_H(value) LPC_SCT->MATCHREL_L[1] = value;
#define reload_deactivate_H(value) LPC_SCT->MATCHREL_H[1] = value;

#endif
