
/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

/* Uses following resources: */
/* [4 events, 2+2 states, 0 inputs, 4 outputs, 4 match regs, 0 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{

/* MATCH/CAPTURE registers */
LPC_SCT->REGMODE_L = 0x0000;         /* L: 2x MATCH, 0x CAPTURE, 2 unused */
LPC_SCT->REGMODE_H = 0x0000;             /* H: 2x MATCH, 0x CAPTURE, 2 unused */
LPC_SCT->MATCH_L[0] = counterL_stop;
LPC_SCT->MATCHREL_L[0] = counterL_stop;
LPC_SCT->MATCH_H[0] = counterL_start;
LPC_SCT->MATCHREL_H[0] = counterL_start;
LPC_SCT->MATCH_L[1] = counterH_start;
LPC_SCT->MATCHREL_L[1] = counterH_start;
LPC_SCT->MATCH_H[1] = counterH_stop;
LPC_SCT->MATCHREL_H[1] = counterH_stop;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x0000000A;        /* COUNTER_L_RUN */
LPC_SCT->OUT[0].CLR = 0x00000005;
LPC_SCT->OUT[1].SET = 0x00000005;        /* COUNTER_H_RUN */
LPC_SCT->OUT[1].CLR = 0x0000000A;
LPC_SCT->OUT[2].SET = 0x00000004;        /* STATE_1 */
LPC_SCT->OUT[2].CLR = 0x00000001;
LPC_SCT->OUT[3].SET = 0x00000002;        /* STATE_2 */
LPC_SCT->OUT[3].CLR = 0x00000008;
  /* Unused outputs must not be affected by any event */
/*LPC_SCT->OUT[4].SET = 0;*/
/*LPC_SCT->OUT[4].CLR = 0;*/
/*LPC_SCT->OUT[5].SET = 0;*/
/*LPC_SCT->OUT[5].CLR = 0;*/
/*LPC_SCT->OUT[6].SET = 0;*/
/*LPC_SCT->OUT[6].CLR = 0;*/
/*LPC_SCT->OUT[7].SET = 0;*/
/*LPC_SCT->OUT[7].CLR = 0;*/
/*LPC_SCT->OUT[8].SET = 0;*/
/*LPC_SCT->OUT[8].CLR = 0;*/
/*LPC_SCT->OUT[9].SET = 0;*/
/*LPC_SCT->OUT[9].CLR = 0;*/
/*LPC_SCT->OUT[10].SET = 0;*/
/*LPC_SCT->OUT[10].CLR = 0;*/
/*LPC_SCT->OUT[11].SET = 0;*/
/*LPC_SCT->OUT[11].CLR = 0;*/
/*LPC_SCT->OUT[12].SET = 0;*/
/*LPC_SCT->OUT[12].CLR = 0;*/
/*LPC_SCT->OUT[13].SET = 0;*/
/*LPC_SCT->OUT[13].CLR = 0;*/
/*LPC_SCT->OUT[14].SET = 0;*/
/*LPC_SCT->OUT[14].CLR = 0;*/
/*LPC_SCT->OUT[15].SET = 0;*/
/*LPC_SCT->OUT[15].CLR = 0;*/
LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x0000000E) | 0x00000001;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x00005000;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[0].STATE = 0x00000002;
LPC_SCT->EVENT[1].CTRL = 0x0000D010;     /* H: --> state State2 */
LPC_SCT->EVENT[1].STATE = 0x00000001;
LPC_SCT->EVENT[2].CTRL = 0x0000D001;     /* L: --> state State1 */
LPC_SCT->EVENT[2].STATE = 0x00000001;
LPC_SCT->EVENT[3].CTRL = 0x00005011;     /* H: --> state H_ENTRY */
LPC_SCT->EVENT[3].STATE = 0x00000002;
  /* Unused events must not have any effect */
LPC_SCT->EVENT[4].STATE = 0;
LPC_SCT->EVENT[5].STATE = 0;
/*LPC_SCT->EVENT[6].STATE = 0;*/
/*LPC_SCT->EVENT[7].STATE = 0;*/
/*LPC_SCT->EVENT[8].STATE = 0;*/
/*LPC_SCT->EVENT[9].STATE = 0;*/
/*LPC_SCT->EVENT[10].STATE = 0;*/
/*LPC_SCT->EVENT[11].STATE = 0;*/
/*LPC_SCT->EVENT[12].STATE = 0;*/
/*LPC_SCT->EVENT[13].STATE = 0;*/
/*LPC_SCT->EVENT[14].STATE = 0;*/
/*LPC_SCT->EVENT[15].STATE = 0;*/

/* STATE registers */
LPC_SCT->STATE_L = 0;
LPC_SCT->STATE_H = 0;

/* state names assignment: */
  /* State L 0: L_ENTRY */
  /* State L 1: State1 */
  /* State H 0: H_ENTRY */
  /* State H 1: State2 */

/* CORE registers */
LPC_SCT->START_L = 0x000A;
LPC_SCT->STOP_L =  0x0005;
LPC_SCT->HALT_L =  0x0000;
LPC_SCT->LIMIT_L = 0x0005;
LPC_SCT->START_H = 0x0005;
LPC_SCT->STOP_H =  0x000A;
LPC_SCT->HALT_H =  0x0000;
LPC_SCT->LIMIT_H = 0x000A;
LPC_SCT->EVEN =    0x00000000;
/*LPC_SCT->DMA0REQUEST = 0x00000000;*/
/*LPC_SCT->DMA1REQUEST = 0x00000000;*/

}
